- hosts: localhost
  tasks:
  - name: Deploy app
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: app
          namespace: default
        spec:
          replicas: 2
          selector: 
            matchLabels: 
              role: app
          template:
            metadata:
              labels:
                role: app
            spec:
              containers:
              - name: app
                image: "{{ image_id }}"
                imagePullPolicy: IfNotPresent
                ports:
                - containerPort: 8080
      validate_certs: no
  - name: Expose app
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Service
        metadata:
          name: hello-svc
        spec:
          selector:
            role: app
          ports:
            - protocol: TCP
              port: 80
              targetPort: 8080
              nodePort: 32000
          type: NodePort        
